pub_key:
    - 48
    - 72
    - 2
    - 65
    - 0
    - 182
    - 90
    - 43
    - 230
    - 1
    - 24
    - 116
    - 11
    - 0
    - 141
    - 209
    - 99
    - 3
    - 14
    - 24
    - 33
    - 252
    - 239
    - 12
    - 89
    - 164
    - 67
    - 211
    - 83
    - 130
    - 218
    - 239
    - 162
    - 38
    - 111
    - 134
    - 141
    - 39
    - 152
    - 96
    - 122
    - 221
    - 193
    - 58
    - 151
    - 15
    - 61
    - 36
    - 82
    - 183
    - 0
    - 12
    - 28
    - 128
    - 191
    - 47
    - 201
    - 49
    - 185
    - 88
    - 203
    - 255
    - 122
    - 107
    - 110
    - 97
    - 84
    - 160
    - 153
    - 2
    - 3
    - 1
    - 0
    - 1
host: localhost
port: 8080
projects:
    - id: test
      repo: https://github.com/DecentralCardgame/frontend
      location: ~/frontend_buid_test
      script: |
        echo "hmm"
        echo 'es geht'
        sleep 3
        echo 'jaja'
        >&2 echo "nein"