pub_key:
    - 48
    - 72
    - 2
    - 65
    - 0
    - 197
    - 123
    - 4
    - 96
    - 193
    - 77
    - 51
    - 225
    - 151
    - 59
    - 13
    - 94
    - 139
    - 28
    - 25
    - 113
    - 125
    - 250
    - 211
    - 3
    - 0
    - 92
    - 106
    - 206
    - 141
    - 251
    - 137
    - 192
    - 45
    - 249
    - 168
    - 41
    - 48
    - 240
    - 198
    - 211
    - 24
    - 95
    - 244
    - 242
    - 54
    - 72
    - 57
    - 60
    - 44
    - 53
    - 163
    - 155
    - 43
    - 43
    - 26
    - 125
    - 39
    - 94
    - 79
    - 202
    - 27
    - 86
    - 123
    - 2
    - 2
    - 139
    - 103
    - 183
    - 2
    - 3
    - 1
    - 0
    - 1
host: localhost
port: 8080
projects:
    - id: test
      repo: https://github.com/DecentralCardgame/frontend
      location: ~/frontend_buid_test
      script: |
        npm i && npm run build