pub_key:
    - 48
    - 72
    - 2
    - 65
    - 0
    - 206
    - 229
    - 195
    - 200
    - 53
    - 192
    - 116
    - 224
    - 120
    - 235
    - 210
    - 220
    - 14
    - 15
    - 37
    - 1
    - 200
    - 11
    - 83
    - 100
    - 21
    - 194
    - 172
    - 126
    - 236
    - 31
    - 30
    - 2
    - 242
    - 91
    - 28
    - 33
    - 103
    - 92
    - 76
    - 102
    - 241
    - 175
    - 52
    - 47
    - 50
    - 109
    - 157
    - 24
    - 169
    - 25
    - 66
    - 192
    - 241
    - 201
    - 32
    - 125
    - 119
    - 9
    - 216
    - 232
    - 7
    - 219
    - 81
    - 173
    - 105
    - 100
    - 35
    - 39
    - 2
    - 3
    - 1
    - 0
    - 1
host: localhost
port: 8080
projects:
    - id: test
      repo: https://github.com/DecentralCardgame/frontend
      location: ~/frontend_buid_test
      script: |
        npm i && npm run build